version: "3.8"

services:
   mysql:
      image: mysql
      environment:
         MYSQL_ROOT_PASSWORD: secret
         MYSQL_DATABASE: agendamentoemaildb
      ports:
         - "3306:3306"
      volumes:
         - ./db:/docker-entrypoint-initdb.d
      networks:
         - alura-network
         
   adminer:
      image: adminer
      ports: 
         - "8180:8080"
      networks:
         - alura-network
         
networks:
   alura-network:
      driver: bridge
      